apiVersion: v1
kind: Service
metadata:
  name: helm-app-db
spec:
  selector:
    app: helm-app
    component: postgres
  ports:
    - protocol: TCP
      port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}