apiVersion: v1
kind: Service
metadata:
  name: helm-app
spec:
  type: ClusterIP
  selector:
    app: helm-app
  ports:
    - protocol: TCP
      port: {{ .Values.app.port }}
      targetPort: {{ .Values.app.port }}